#!/bin/bash
input_dir="$1"
output_dir="$2"
find "$input_dir" -type f | while read file; do
        filename=$(basename "$file")
        base="${file%.*}"
        extension="${filename##*.}"
        if [ -f "$output_dir/$filename" ]; then
                i=1
                while [ -f "$output_dir/${base}${i}.$extension" ]; do
                        ((i+=1))
                done
                cp "$file" "$output_dir/${base}${i}.$extension"
        else
                cp "$file" "$output_dir/$filename"
        fi
done
